export const gallery = [
  {
    src: "/gallery/magical-unicorns.webp",
    alt: "Magical Unicorns banner: a pink unicorn kicking a purple soccer ball.",
    title: "Magical Unicorns",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/emerald-dragons.webp",
    alt: "Emerald Dragons banner: a green dragon diving for a soccer ball in a stadium.",
    title: "Emerald Dragons",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/ice-dragons.webp",
    alt: "A printed Ice Dragons banner on the floor, with a teal dragon crest, grommets, and a soccer ball.",
    title: "Ice Dragons",
    width: 1024,
    height: 629,
  },
  {
    src: "/gallery/blazing-bumblebees.webp",
    alt: "Blazing Bumblebees banner: a bee in a yellow jersey with one foot on a soccer ball at sunset.",
    title: "Blazing Bumblebees",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/grasshoppers.webp",
    alt: "The Grasshoppers banner: a green grasshopper in cleats kicking a soccer ball through tall grass.",
    title: "The Grasshoppers",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/blazing-bumblebees-girls.webp",
    alt: "Blazing Bumblebees Girls banner: a cartoon bee flying beside bold black and yellow lettering and a soccer ball.",
    title: "Blazing Bumblebees Girls",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/black-magic.webp",
    alt: "Black Magic banner: a player in a number 10 jersey standing on a soccer ball under a full moon.",
    title: "Black Magic",
    width: 1024,
    height: 614,
  },
] as const;
