export const gallery = [
  {
    src: "/gallery/fire-raindrops.webp",
    alt: "Fire Raindrops banner: cream brush lettering and ten player names around a soccer ball on a deep red field.",
    title: "Fire Raindrops",
    summary: "A red youth banner with the team name in the center and the roster split down both sides.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/pink-mermacorns.webp",
    alt: "Pink Mermacorns banner: a pink mermaid unicorn leaping through waves beside a pink soccer ball.",
    title: "Pink Mermacorns",
    summary: "A pink mascot banner, with a mermaid unicorn, waves, and a matching soccer ball.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/magical-unicorns.webp",
    alt: "Magical Unicorns banner: a pink unicorn kicking a purple soccer ball.",
    title: "Magical Unicorns",
    summary: "A unicorn mid-kick, with script lettering over a purple field and a goal in the distance.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/emerald-dragons.webp",
    alt: "A printed Emerald Dragons banner: a green dragon diving for a soccer ball in a stadium.",
    title: "Emerald Dragons",
    summary: "A green dragon diving for the ball, set in a stadium instead of on a plain background.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/ice-dragons.webp",
    alt: "Ice Dragons banner: a teal dragon crest above a soccer ball.",
    title: "Ice Dragons",
    summary: "A teal crest: dragon head, soccer ball, and plenty of open space around the name.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/grasshoppers.webp",
    alt: "The Grasshoppers banner: a green grasshopper in cleats kicking a soccer ball through tall grass.",
    title: "The Grasshoppers",
    summary: "A grasshopper in cleats kicking through tall grass, with the name tucked in the corner.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/blazing-bumblebees-girls.webp",
    alt: "Blazing Bumblebees Girls banner: a cartoon bee flying beside bold black and yellow lettering and a soccer ball.",
    title: "Blazing Bumblebees Girls",
    summary: "Black and yellow lettering, a bee, and a ball. Made for a girls team.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/black-magic.webp",
    alt: "Black Magic banner: a player in a number 10 jersey standing on a soccer ball under a full moon.",
    title: "Black Magic",
    summary: "A number 10 standing on the ball under a full moon. Dark field, cream type.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/little-lions.webp",
    alt: "Little Lions banner: a yellow lion cub reaching for a soccer ball beside brush-lettered team name.",
    title: "Little Lions",
    summary: "A lion cub reaching for the ball, with the team name in brush letters.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/midnight-wolves.webp",
    alt: "Midnight Wolves banner: a wolf beside a soccer ball under a full moon, with rounded cream lettering.",
    title: "Midnight Wolves",
    summary: "A wolf and a ball under a full moon, with rounded cream lettering.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/neon-cobras.webp",
    alt: "Neon Cobras banner: a green cobra coiled through neon lettering on a black field.",
    title: "Neon Cobras",
    summary: "A green cobra threaded through neon type on a black banner.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/cosmic-comets.webp",
    alt: "Cosmic Comets banner: cream lettering and a soccer ball on an orbital path against a purple star field.",
    title: "Cosmic Comets",
    summary: "Cream lettering and a ball on an orbit, set on a purple star field.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/red-turtles.webp",
    alt: "Red Turtles banner: cream lowercase lettering beside a cropped soccer ball on a deep red field.",
    title: "Red Turtles",
    summary: "Lowercase cream type beside a cropped ball, on a deep red field.",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/thunder-sharks.webp",
    alt: "Thunder Sharks banner: cream arched lettering over a shark fin cutting through the water, on a gray field marked like a soccer pitch.",
    title: "Thunder Sharks",
    summary: "Arched lettering over a shark fin, on a gray field marked like a pitch.",
    width: 1024,
    height: 614,
  },
] as const;
