export const gallery = [
  {
    src: "/gallery/fire-raindrops.webp",
    alt: "Fire Raindrops banner: cream brush lettering and ten player names around a soccer ball on a deep red field.",
    title: "Fire Raindrops",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/pink-mermacorns.webp",
    alt: "Pink Mermacorns banner: a pink mermaid unicorn leaping through waves beside a pink soccer ball.",
    title: "Pink Mermacorns",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/magical-unicorns.webp",
    alt: "Magical Unicorns banner: a pink unicorn kicking a purple soccer ball.",
    title: "Magical Unicorns",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/emerald-dragons.webp",
    alt: "A printed Emerald Dragons banner: a green dragon diving for a soccer ball in a stadium.",
    title: "Emerald Dragons",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/ice-dragons.webp",
    alt: "Ice Dragons banner: a teal dragon crest above a soccer ball.",
    title: "Ice Dragons",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/grasshoppers.webp",
    alt: "The Grasshoppers banner: a green grasshopper in cleats kicking a soccer ball through tall grass.",
    title: "The Grasshoppers",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/blazing-bumblebees-girls.webp",
    alt: "Blazing Bumblebees Girls banner: a cartoon bee flying beside bold black and yellow lettering and a soccer ball.",
    title: "Blazing Bumblebees Girls",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/black-magic.webp",
    alt: "Black Magic banner: a player in a number 10 jersey standing on a soccer ball under a full moon.",
    title: "Black Magic",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/little-lions.webp",
    alt: "Little Lions banner: a yellow lion cub reaching for a soccer ball beside brush-lettered team name.",
    title: "Little Lions",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/midnight-wolves.webp",
    alt: "Midnight Wolves banner: a wolf beside a soccer ball under a full moon, with rounded cream lettering.",
    title: "Midnight Wolves",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/neon-cobras.webp",
    alt: "Neon Cobras banner: a green cobra coiled through neon lettering on a black field.",
    title: "Neon Cobras",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/cosmic-comets.webp",
    alt: "Cosmic Comets banner: cream lettering and a soccer ball on an orbital path against a purple star field.",
    title: "Cosmic Comets",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/red-turtles.webp",
    alt: "Red Turtles banner: cream lowercase lettering beside a cropped soccer ball on a deep red field.",
    title: "Red Turtles",
    width: 1024,
    height: 614,
  },
  {
    src: "/gallery/thunder-sharks.webp",
    alt: "Thunder Sharks banner: cream arched lettering over a shark fin cutting through the water, on a gray field marked like a soccer pitch.",
    title: "Thunder Sharks",
    width: 1024,
    height: 614,
  },
] as const;
